config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  # resources map 7 HTTP verbs
  # GET       /articles
  # GET       /articles/new
  # POST      /articles
  # GET       /articles/:id
  # GET       /articles/:id/edit
  # PATCH/PUT /articles/:id
  # DELETE    /articles/:id
  resources :articles do
    resources :comments
  end
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {minimum:10, maximum:100}
  validates :slug, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count 
      where(status: "public").count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dave", password: "megadeth", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show 
    @article = Article.find(params[:id])
  end

  def new  
    @article = Article.new  
  end

  def create 
    @article = Article.new(article_params)

    if @article.save 
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])

    if @article.update(article_params) 
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end  

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  # Using a private method to encapsulate the permissible parameters
  # is just a good pattern since you'll be able to reuse the same
  # permit list between create and update. Also, you can specialize
  # this method with per-user checking of permissible attributes.
  # https://guides.rubyonrails.org/action_controller_overview.html#strong-parameters
  private
  def article_params
    params.require(:article).permit(:title, :slug, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dave", password: "megadeth", except: [:index, :show]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def detroy
      @article = Article.find(params[article_id])
      @comment = @article.comment.find(params[:id])
      @comment.destroy
      
      redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article, class: "flex flex-col gap-2" do |form| %>
  <div>
    <%= form.label :title, class: "text-white" %><br>
    <%= form.text_field :title, class: "rounded-md" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div class="text-red-700"><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :slug, class: "text-white" %><br>
    <%= form.text_field :slug, class: "rounded-md" %><br>
    <% article.errors.full_messages_for(:slug).each do |message| %>
      <div class="text-red-700"><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body, class: "text-white" %><br>
    <%= form.text_area :body, class: "rounded-md" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div class="text-red-700"><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :status, class: "text-white" %><br>
    <%= form.select :status, Visible::VALID_STATUSES, { selected: article.status || 'public' }, class: "rounded-md" %>
  </div>
  <%= form.submit "Create", class: "cursor-pointer border-blue-800 max-w-[130px] flex justify-center bg-blue-700 text-white rounded-lg text-center" %>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-blue-800 mb-2">Edit Article</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-white">Articles</h1>
<p class="text-white">
  Our blog has <%= Article.public_count %> articles and counting!
</p>
<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article, class: "text-white" %>
      </li>
    <% end %>
  <% end %>
</ul>
<%= link_to "New Article", new_article_path, class: "h-[3rem] py-2 px-2 rounded-md font-bold text-[#2B306A] bg-[#646EE4] no-underline" %>

app/views/articles/new.html.erb
<h1 class="text-blue-800 mb-2">New Article</h1>
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<section class="flex items-center gap-10 justify-center">
  <div>
    <h2 class="text-cyan-400"><%= @article.slug %></h2>
    <div class="card w-96 bg-[#1D232A] shadow-xl rounded-lg">
      <figure><img src="https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg" alt="Shoes" /></figure>
      <div class="pb-2 px-3 text-white">
        <h2 class="card-title text-white"><%= @article.title %></h2>
        <p><%= @article.body %></p>
        <div class="flex justify-end gap-2">
          <%= link_to "Edit post", edit_article_path(@article), class: "flex items-center no-underline h-[3rem] px-2 rounded-md font-bold text-[#2B306A] bg-[#646EE4]" %>
          <%= link_to "Delete post", article_path(@article), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      }, class: "flex items-center no-underline h-[3rem] px-2 rounded-md font-bold text-white bg-red-500" %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <h2 class="text-white">Add a comment:</h2>
    <%= render 'comments/form' %>
  </div>
</section>
<h2 class="text-white">Comments</h2>
<section class="space-y-4">
  <%= render @article.comments %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <div class="w-full p-2 bg-[#1D232A] shadow-xl rounded-lg">
    <p class="text-white">
      <strong class="text-gray-400">Commenter:</strong>
      <%= comment.commenter %>
    </p>
    <p class="text-white">
      <strong class="text-gray-400">Comment:</strong>
      <%= comment.body %>
    </p>
    <p class="w-full flex justify-end">
      <%= link_to "Delete Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                }, class: "max-w-[160px] text-center justify-center flex items-center no-underline h-[3rem] px-2 rounded-md font-bold text-white bg-red-500"%>
    </p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, Comment.new ], class: "flex flex-col gap-1" do |form| %>
  <p>
    <%= form.label :commenter, class: "text-white" %><br>
    <%= form.text_field :commenter, class: "rounded-md" %>
  </p>
  <p>
    <%= form.label :body,class: "text-white" %><br>
    <%= form.text_area :body, class: "rounded-md" %>
  </p>
  <p>
    <%= form.label :status, class: "text-white" %><br>
    <%= form.select :status, Visible::VALID_STATUSES, { selected: 'public' }, class: "rounded-md" %>
  </p>
  <%= form.submit "Add comment", class: "cursor-pointer border-blue-800 max-w-[130px] flex justify-center bg-blue-700 text-white rounded-lg text-center" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="prose bg-slate-800 text-dark mx-auto w-full">
    <main class="p-5">
      <%= yield %>
    </main>
  </body>
</html>